NDefines.NGame.START_DATE = "171.1.1.12"
NDefines.NGame.END_DATE = "1000.1.1.1"
NDefines.NGame.MAP_SCALE_PIXEL_TO_KM = 7.114
NDefines.NGame.FUEL_RESOURCE = "food"
NDefines.NGame.HANDS_OFF_START_TAG = "KZK"

NDefines.NDiplomacy.TENSION_TIME_SCALE_START_DATE = "171.1.1.12"
NDefines.NDiplomacy.IDEOLOGY_JOIN_FACTION_MIN_LEVEL = 0.0

NDefines.NCountry.EVENT_PROCESS_OFFSET = 1

NDefines.NResistance.RESISTANCE_TARGET_MODIFIER_PER_COMPLIANCE = -1.0
NDefines.NResistance.INITIAL_HISTORY_COMPLIANCE = 30.0

NDefines.NPolitics.BASE_POLITICAL_POWER_INCREASE = 2

NDefines.NAI.IMPORTANT_VICTORY_POINT = 15

NDefines.NAI.IMPORTANT_VICTORY_POINT = 15
NDefines.NAI.BUILDING_TARGETS_BUILDING_PRIORITIES = {
	'lumber_mill',
}

NDefines_Graphics.NGraphics.VICTORY_POINT_MAP_ICON_AFTER = {0, 2}
NDefines_Graphics.NGraphics.VICTORY_POINT_MAP_ICON_TEXT_CUTOFF = {300, 600, 1200}
NDefines_Graphics.NGraphics.VICTORY_POINTS_DISTANCE_CUTOFF = {300, 600, 1200}
NDefines_Graphics.NGraphics.RESOURCE_MAP_ICON_TEXT_CUTOFF = 2000
NDefines_Graphics.NGraphics.CAPITAL_ICON_CUTOFF = 1500
NDefines_Graphics.NGraphics.WEATHER_DISTANCE_CUTOFF = 1200
NDefines_Graphics.NGraphics.WEATHER_ZOOM_IN_CUTOFF = 1
NDefines_Graphics.NGraphics.WEATHER_PLAYBACK_RATE = 0.25
NDefines_Graphics.NGraphics.WEATHER_PLAYBACK_RATE_CUTOFF = 400
NDefines_Graphics.NGraphics.COUNTRY_COLOR_SATURATION_MODIFIER = 0.8
